apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: openfaas
  labels:
    app: of-auth
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: of-auth
